name: checkov

permissions: read-all

on:
  push:
    branches: ["main", "deploy/azure"]
  pull_request:
    branches: ["main", "deploy/azure"]

jobs:
  scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v3

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif