name: Security checks

permissions: read-all

on: [push, pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run TruffleHog
        run: |
          docker run --rm -it -v $(pwd):/pwd -w /pwd ghcr.io/trufflesecurity/trufflehog:latest \
            filesystem --path=. --fail
  
  bandit:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Perform Bandit Analysis
        uses: PyCQA/bandit-action@v1

  detect-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install detect-secrets
        run: pip install detect-secrets

      - name: Scan for secrets
        run: detect-secrets scan --all-files > .secrets.baseline

      - name: Audit baseline
        run: detect-secrets audit .secrets.baseline
